version: 2
updates:
  # Backend package dependencies configuration
  - package-ecosystem: "npm"
    directory: "/src/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "security"
    reviewers:
      - "CODEOWNERS"
    open-pull-requests-limit: 10
    security-updates-only: false
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    rebase-strategy: "auto"

  # Frontend package dependencies configuration  
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "security"
    reviewers:
      - "CODEOWNERS"
    open-pull-requests-limit: 10
    security-updates-only: false
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    rebase-strategy: "auto"