apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: identity-matrix-frontend
  namespace: identity-matrix
  labels:
    app: identity-matrix
    component: frontend
    managed-by: kubernetes
    environment: production

spec:
  # Target the frontend deployment for auto-scaling
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: identity-matrix-frontend

  # Replica range to maintain high availability (99.9% uptime)
  minReplicas: 3
  maxReplicas: 10

  # Resource metrics for scaling decisions
  metrics:
    # CPU-based scaling
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

    # Memory-based scaling
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

  # Scaling behavior configuration
  behavior:
    # Aggressive scale-up for performance
    scaleUp:
      # Quick reaction to load increases
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2           # Add up to 2 pods
          periodSeconds: 60  # Every minute
      selectPolicy: Max     # Use most aggressive policy

    # Conservative scale-down for stability
    scaleDown:
      # Longer window to prevent thrashing
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1           # Remove 1 pod
          periodSeconds: 60  # Every minute
      selectPolicy: Min     # Use most conservative policy