apiVersion: v1
kind: List
items:
# ServiceAccount for Fluentd
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: fluentd
    namespace: identity-matrix-logging
    labels:
      app: identity-matrix
      component: fluentd

# ClusterRole for Fluentd permissions
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: fluentd
    labels:
      app: identity-matrix
      component: fluentd
  rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]

# ClusterRoleBinding to bind ServiceAccount to ClusterRole
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: fluentd
    labels:
      app: identity-matrix
      component: fluentd
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: fluentd
  subjects:
  - kind: ServiceAccount
    name: fluentd
    namespace: identity-matrix-logging

# ConfigMap containing Fluentd configuration
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: fluentd-config
    namespace: identity-matrix-logging
    labels:
      app: identity-matrix
      component: fluentd
  data:
    fluent.conf: |
      <source>
        @type tail
        path /var/log/containers/*.log
        pos_file /var/log/fluentd-containers.log.pos
        tag kubernetes.*
        read_from_head true
        <parse>
          @type json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </parse>
      </source>

      <filter kubernetes.**>
        @type kubernetes_metadata
        @id filter_kube_metadata
      </filter>

      <match kubernetes.**>
        @type elasticsearch
        @id out_es
        @log_level info
        include_tag_key true
        host elasticsearch.identity-matrix-logging
        port 9200
        logstash_format true
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.system.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 2
          flush_interval 5s
          retry_forever false
          retry_max_interval 30
          chunk_limit_size 2M
          queue_limit_length 8
          overflow_action block
        </buffer>
      </match>

# DaemonSet for Fluentd deployment
- apiVersion: apps/v1
  kind: DaemonSet
  metadata:
    name: fluentd
    namespace: identity-matrix-logging
    labels:
      app: identity-matrix
      component: fluentd
  spec:
    selector:
      matchLabels:
        app: identity-matrix
        component: fluentd
    template:
      metadata:
        labels:
          app: identity-matrix
          component: fluentd
      spec:
        serviceAccount: fluentd
        serviceAccountName: fluentd
        tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        containers:
        - name: fluentd
          image: fluent/fluentd-kubernetes-daemonset:v1.14.6-debian-elasticsearch7-1.1
          env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: elasticsearch.identity-matrix-logging
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENTD_SYSTEMD_CONF
            value: "disable"
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m
          volumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: config-volume
            mountPath: /fluentd/etc/fluent.conf
            subPath: fluent.conf
        volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: config-volume
          configMap:
            name: fluentd-config