apiVersion: v1
kind: List
items:
  # Database credentials secret
  - apiVersion: v1
    kind: Secret
    metadata:
      name: database-credentials
      namespace: identity-matrix
      labels:
        app: identity-matrix
        component: database
      annotations:
        kubernetes.io/description: "Database credentials for Identity Matrix platform"
    type: Opaque
    data:
      # PostgreSQL credentials - Base64 encoded placeholders
      POSTGRES_USER: UE9TVEdSRVNfVVNFUg==  # Replace with actual base64 encoded value
      POSTGRES_PASSWORD: UE9TVEdSRVNfUEFTU1dPUkQ=  # Replace with actual base64 encoded value
      
      # MongoDB credentials - Base64 encoded placeholders
      MONGODB_USERNAME: TU9OR09EQl9VU0VSTkFNRQ==  # Replace with actual base64 encoded value
      MONGODB_PASSWORD: TU9OR09EQl9QQVNTV09SRA==  # Replace with actual base64 encoded value
      
      # Redis credentials - Base64 encoded placeholder
      REDIS_PASSWORD: UkVESVNfUEFTU1dPUkQ=  # Replace with actual base64 encoded value

  # Authentication secrets
  - apiVersion: v1
    kind: Secret
    metadata:
      name: auth-secrets
      namespace: identity-matrix
      labels:
        app: identity-matrix
        component: auth
      annotations:
        kubernetes.io/description: "Authentication secrets for Identity Matrix platform"
    type: Opaque
    data:
      # JWT and session secrets - Base64 encoded placeholders
      JWT_SECRET: SldUX1NFQ1JFVA==  # Replace with actual base64 encoded value
      SESSION_SECRET: U0VTU0lPTl9TRUNSRVQ=  # Replace with actual base64 encoded value
      ENCRYPTION_KEY: RU5DUllQVElPTl9LRVk=  # Replace with actual base64 encoded value

  # OAuth credentials
  - apiVersion: v1
    kind: Secret
    metadata:
      name: oauth-credentials
      namespace: identity-matrix
      labels:
        app: identity-matrix
        component: oauth
      annotations:
        kubernetes.io/description: "OAuth credentials for Identity Matrix platform"
    type: Opaque
    data:
      # OAuth configuration - Base64 encoded placeholders
      OAUTH_CLIENT_ID: T0FVVEhfQ0xJRU5UX0lE  # Replace with actual base64 encoded value
      OAUTH_CLIENT_SECRET: T0FVVEhfQ0xJRU5UX1NFQ1JFVA==  # Replace with actual base64 encoded value
      OAUTH_CALLBACK_URL: aHR0cHM6Ly9pZGVudGl0eS1tYXRyaXguZXhhbXBsZS5jb20vYXV0aC9jYWxsYmFjaw==  # Replace with actual base64 encoded value